export enum ThemeColor {
  PRIMARY = 'Primary',
  SECONDARY = 'Secondary',
  SUCCESS = 'Success',
  INFO = 'Info',
  WARNING = 'Warning',
  DANGER = 'Danger',
  BLACK = 'Black',
  DARK = 'Dark',
  MEDIUM = 'Medium',
  LIGHT = 'Light',
  WHITE = 'White',
  ACCENT_1 = 'Accent1',
  ACCENT_2 = 'Accent2',
  ACCENT_3 = 'Accent3',
  TRANSPARENT = 'transparent',
}
